module.exports = [
{ codigo: 1, 
    titulo: 'Misantropo', 
    reparto: ['Shailene Woodley','Ben Mendelsohn', 'Ralph Ineson'], 
    categoria: 'Suspenso', 
    genero: 'Suspenso', 
    sinopsis: 'La joven, talentosa, pero traumatizada agente de policía Eleanor ayuda al FBI a localizar a un francotirador que está perpetrando asesinatos en masa en Baltimore. La mente atormentada de Eleanor es la única que puede predecir sus movimientos.', 
    trailer: 'https://www.youtube.com/watch?v=sGjJhdTqfZc'},
{   codigo: 2, 
    titulo: 'The Mother', 
    reparto: ['Jennifer Lopez', 'Omari Hardwick', 'Joseph Fiennes', 'Gael García Bernal'], 
    categoria: 'Accion', 
    genero: 'Accion', 
    sinopsis: 'Una agente del Gobierno adopta una nueva identidad y abandona a su hija recién nacida para protegerla de sus enemigos. Años más tarde, unos criminales secuestran a la chica, lo que obliga a la madre a abandonar el anonimato para salvarla.', 
    trailer: 'https://www.youtube.com/watch?v=8BFdFeOS3oM'},
{   codigo: 3, 
    titulo: 'Evil Dead: El Despertar', 
    reparto: ['Alyssa Sutherland', 'Morgan Davies'], 
    categoria: 'Terror', 
    genero: 'Terror', 
    sinopsis: 'En un edificio de apartamentos de Los Ángeles, dos hermanas luchan contra los demonios sedientos de sangre que han salido de un libro antiguo.', 
    trailer: 'https://www.youtube.com/watch?v=vwewz36Z6kU'},
{   codigo: 4, 
    titulo: 'A la deriva', 
    reparto: ['Shailene Woodley', 'Sam Claflin', 'Tami Oldham Ashcraft', 'Grace Palmer'], 
    categoria:'Drama', 
    genero: 'Drama', 
    sinopsis: 'Un huracán devastador destroza el velero en el que viajan Tami y Richard. Este último queda gravemente herido y Tami tiene que tomar el mando del velero averiado y encontrar ayuda en alta mar. No les queda comida ni agua, solo esperanza.', 
    trailer: 'https://www.youtube.com/watch?v=SM9JJmwxBPo'},
{   codigo: 5, 
    titulo: 'Bajo la misma estrella', 
    reparto: ['Shailene Woodley', 'Ansel Elgort'], 
    categoria: 'Romance', 
    genero: 'Drama', 
    sinopsis: 'Dos adolescentes pacientes de cáncer inician un viaje para reafirmar sus vidas y visitar a un escritor solitario en Ámsterdam.', 
    trailer: 'https://www.youtube.com/watch?v=9ItBvH5J6ss'},
{   codigo: 6, 
    titulo: 'The Flash', 
    reparto: ['Ezra Miller', 'Michael Keaton', 'Ben Affleck', 'Sasha Calle', 'Kiersey Clemons'], 
    categoria: 'Accion', 
    genero: 'Fantasia', 
    sinopsis: 'Flash viaja a través del tiempo para evitar el asesinato de su madre, pero, sin saberlo, provoca una serie de cambios que originan la creación de un multiverso.', 
    trailer: 'https://www.youtube.com/watch?v=Dg0KNwCXdd0'}];


